Content
vishvAsa/vedAH pull request #141
Opened 2021-08-17 19:29 UTC by kishorsharma77

2021-08-18 00:08 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +तत्र'यस्य पितापितामह' इत्युपक्रमे 'यस्ये'त्येकवचनमन्तेऽ'प्यध्याप्य इति । मध्ये तु 'ब्रह्महसंस्तुताः' 'तेषामभ्यागमनं' 'तेषामिच्छता'मिति बहुवचनम् । तत्रोपक्रमोपसहारानुसारेण माणवकस्यैव प्रायश्चित्तमुपनय
तत्र इत्यस्मात् परं रिक्तस्थानम् अस्तु।

2021-08-18 00:57 UTC, vvasuki requested changes
markdown सञ्चिकानाम् hugo इत्यादिभिः परीक्षणम् इष्यते।

2021-08-18 00:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  regaon
निष्कासनीया पङ्क्तिः।

2021-08-18 00:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  RMERE
इमा अपि निष्कासनीयाः। एवम् अन्यत्र।

2021-08-18 00:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  (१)प्रणिपत्य महादेव हरदत्तेन धीमता।
कुत एतन्न शोधितम्? महादेवम् इति।

2021-08-18 00:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +१. मातामहमहाशल महस्तदपितामहम् ।
पुस्तकेष्व् एवम् पादटिप्पनीः पृष्ठपादेषु स्थाप्येरन्। नैवम् अत्र। उचितस्थानेषु प्रापणीयाः। यथाऽत्र - (१) इत्यस्य सम्बन्ध आदिमश्लोकेनास्ति। तावत् तत्रैव स्थापनीयम्। न कदाचिद् अपि पादटिप्पनीभिर् वाक्यं छिद्येत - यथाऽत्र "तत्र प्रवृत्तिप्रयोजनो विधि:-(४) सन्ध्याेश्च" इत्यादिकं वाक्यं छिन्नम्। तद् वाक्यखण्डम् अग्रे सारयतु। तत्सम्बद्धाम् अपि `४. आप० ध० १.३०.८.` इति पादटिप्पनीम्।

पादटिप्पनीनां प्रस्तुतिर् एवम् पङ्तिश  इष्यते -

```
- २. दक्षस्मृ० अ० २ श्लो २९ 'यदन्यत् कुरुते कर्म न तस्य फलभाभवेत् । इति तस्योत्तरार्धम् ।
- ३. गौ० ध० २१. ४."अशुचेर्द्विजाती"ति. घ. पु
```

एवं सर्वत्र।

2021-08-18 00:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +बहिर्ग्रामादासनं वाग्यतश्चेत्यादिः । निवृत्तिप्रयोजनावितरौ। (१) 'प्राङ् मुखोऽन्नानि भुञ्जीते'ति नियमविधिः । क्षुदुपघातार्था भोजने प्रवृत्तिः । शक्यं च (२)यत्किञ्चिद्दिङ्मुखेनापि भुञ्जानेन क्षुदुपहन्त
किम् अत्र `__` इत्यधिकं त्यक्तम्?

तथा पाठखण्डानां (paragraph इत्येषां) विवेकः सम्यक् स्यात् यथा hugo-इत्यादिभिर् जनिते जालपुटे सम्यग् दृश्येत - रिक्तपङ्क्ति-रिक्तस्थानादियोजनैः।

2021-08-18 00:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  धर्माख्यप्रश्नयोरेषा क्रियते वृत्तिरुज्ज्वला ॥ १॥ अथातस्सामयाचारिकान् धर्मान् व्याख्यास्यामः ॥ १॥
अथातस्सामयाचारिकान् धर्मान् व्याख्यास्यामः ॥ १॥ इति सूत्रम् भिन्न पङ्क्ताव् अस्तु। तत्प्रस्तुतिर् एवम् -
```

## सूत्रम् 
अथातस्सामयाचारिकान् धर्मान् व्याख्यास्यामः ॥ १॥

### टिप्पनी 
अथशब्द आनन्तर्ये । अतश्शब्दो हेतौ । …
```
इति लेख्यम्।

एवं सर्वत्र (अग्रे तु विशेषो वक्ष्यते)।

2021-08-18 00:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +वक्तव्यो वा विशेष , तमाह---
अत्र प्रस्तुतिर् एवम् - 
```
## सूत्रम् 
वेदाश्च ॥ ३॥

### प्रस्तावः
वक्तव्यो वा विशेष , तमाह---

### टिप्पनी
चोऽवधारणे । वेदा एव मूलप्रमाणं धर्माधर्मयोः ।…

```
एवम् अन्यत्र तादृशेषु स्थलेषु।

2021-08-18 00:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  (२) सुगतो यदि धर्मज्ञः कपिलो नेति का प्रमा।
उदाहृतश्लोकानां ग्रन्थान्तरगतवाक्यानां च प्रस्तुतिर् एवम् - 
```
… यथाऽऽहुः —

> (२) सुगतो यदि धर्मज्ञः कपिलो नेति का प्रमा।
> तावुभौ यदि धर्मज्ञौ मतभेदः कथं तयोः ॥ 

इति ।

```

2021-08-19 03:46 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +तत्र'यस्य पितापितामह' इत्युपक्रमे 'यस्ये'त्येकवचनमन्तेऽ'प्यध्याप्य इति । मध्ये तु 'ब्रह्महसंस्तुताः' 'तेषामभ्यागमनं' 'तेषामिच्छता'मिति बहुवचनम् । तत्रोपक्रमोपसहारानुसारेण माणवकस्यैव प्रायश्चित्तमुपनय
समाहितम्

2021-08-19 03:46 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  regaon
समाहितम्

2021-08-19 03:46 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  RMERE
समाहितम्

2021-08-19 03:47 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  (१)प्रणिपत्य महादेव हरदत्तेन धीमता।
समाहितम्। पुस्तके तथैव अस्तीत्यतः, अनवधानेन तथैव त्यक्तम्।

2021-08-19 03:47 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +१. मातामहमहाशल महस्तदपितामहम् ।
समाहितम्। अग्रेऽनुवर्तयामि

2021-08-19 03:48 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +बहिर्ग्रामादासनं वाग्यतश्चेत्यादिः । निवृत्तिप्रयोजनावितरौ। (१) 'प्राङ् मुखोऽन्नानि भुञ्जीते'ति नियमविधिः । क्षुदुपघातार्था भोजने प्रवृत्तिः । शक्यं च (२)यत्किञ्चिद्दिङ्मुखेनापि भुञ्जानेन क्षुदुपहन्त
समाहितम्

2021-08-19 03:48 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  धर्माख्यप्रश्नयोरेषा क्रियते वृत्तिरुज्ज्वला ॥ १॥ अथातस्सामयाचारिकान् धर्मान् व्याख्यास्यामः ॥ १॥
समाहितम्

2021-08-19 03:48 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +वक्तव्यो वा विशेष , तमाह---
समाहितम्

2021-08-19 03:49 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
>  (२) सुगतो यदि धर्मज्ञः कपिलो नेति का प्रमा।
समाहितम्।

2021-08-19 06:54 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +१. मातामहमहाशल महस्तदपितामहम् ।
क्व समाहितम्? न दृश्यते। नुदितुं विस्मृतम् ?

2021-08-19 06:55 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +### प्रस्तावः
प्रस्तावभागः सूत्रभागान्तर्गतः स्यात्। नाम - `वेदाश्च` इत्यस्मात् परम्।

2021-08-19 06:55 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +तिष्ठन् भुञ्जीत । न स्नायादिति । तमाह—
प्रस्तावभागः।

2021-08-19 06:57 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +१. मातामहमहाशल महस्तदपितामहम् ।
आदौ `-`चिह्नं न हि दृश्यते। एवम् अग्रेऽपि। hugo परीक्षणं कृतम्?

2021-08-19 08:22 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +१. मातामहमहाशल महस्तदपितामहम् ।
oh  - चिह्नं स्थापनीयम् इति न गृहीतम्। संशोधयामि। hugo परिक्षणं कृतम्

2021-08-19 09:46 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +### प्रस्तावः
##सूत्रम्
वेदाश्च ॥ ३॥  
### प्रस्तावः
वक्तव्यो वा विशेष , तमाह—  


इत्थं वा?

2021-08-19 10:26 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +### प्रस्तावः
आम्।

2021-08-19 10:26 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +१. मातामहमहाशल महस्तदपितामहम् ।
पुनर् न नुदितम् इति भाति। यतः परिवर्तनं न पश्यामि।

2021-08-19 10:36 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +१. मातामहमहाशल महस्तदपितामहम् ।
नुदितमधुना

2021-08-19 10:36 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +### प्रस्तावः
शोधितम्

2021-08-19 10:36 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +तिष्ठन् भुञ्जीत । न स्नायादिति । तमाह—
समाहितम्

2021-08-19 10:42 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +कारण जगता वन्दे कण्ठादुपरि वारणम् ॥१॥ इत्यधिक पाठ• क० पु० ।
पाठः शुद्धो न भाति।

2021-08-19 10:50 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +कारण जगता वन्दे कण्ठादुपरि वारणम् ॥१॥ इत्यधिक पाठ• क० पु० ।
telegram द्वारा प्रेषतिम् वर्तते

2021-08-20 02:48 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/haradatta-TIkA/01/01.md
> +कारण जगता वन्दे कण्ठादुपरि वारणम् ॥१॥ इत्यधिक पाठ• क० पु० ।
शोधितम्

2021-08-20 12:12 UTC, merged