नास्यास्मिंल्लोके प्रत्यापत्तिर्विद्यते कल्मषं तु निर्हण्यते २५
vishvAsa/vedAH pull request #158
Opened 2021-09-13 07:18 UTC by kishorsharma77

2021-09-13 12:12 UTC, vvasuki requested changes

2021-09-13 12:12 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/shaucham/AnandaH.md
> +२२
कुत इयं सङ्ख्या?

2021-09-13 12:12 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/bhojanam.md
> +१७ … आत्ततेजसां भोजनं वर्जयेत् १० … उपेतः स्त्रीणामनुपेतस्य चोच्छिष्टं वर्जयेत् ७
कुत इयं सङ्ख्या व्यर्था?

2021-09-13 12:12 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/shaucham/daNDanam.md
> +२१
कुत इयं सङ्ख्या व्यर्था?

2021-09-13 12:12 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/vANijyam.md
> +२०
कुत इयं सङ्ख्या व्यर्था?

2021-09-13 12:12 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/tattvAni/paapam.md
> +२३ … दोषफलसंशये न तत्कर्तव्यम् १९ एवमध्यायानध्याये २० …क्रोधादींश्च भूतदाहीयान्दोषान्वर्जयेत् २३
कुत इयं सङ्ख्या व्यर्था?

2021-09-15 02:16 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/shaucham/AnandaH.md
> +२२
नेयं धर्मसूत्रसङ्ख्या अपितु पटले अध्यायसङ्ख्या। समाहितम्।

2021-09-15 02:16 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/bhojanam.md
> +१७ … आत्ततेजसां भोजनं वर्जयेत् १० … उपेतः स्त्रीणामनुपेतस्य चोच्छिष्टं वर्जयेत् ७
नेयं धर्मसूत्रसङ्ख्या। समाहितम्

2021-09-15 02:16 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/shaucham/daNDanam.md
> +२१
नेयं धर्मसूत्रसङ्ख्या। समाहितम्

2021-09-15 02:17 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/tattvAni/paapam.md
> +२३ … दोषफलसंशये न तत्कर्तव्यम् १९ एवमध्यायानध्याये २० …क्रोधादींश्च भूतदाहीयान्दोषान्वर्जयेत् २३
नेयं धर्मसूत्रसङ्ख्या। समाहितम्

2021-09-15 02:17 UTC, kishorsharma77 commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/vANijyam.md
> +२०
नेयं धर्मसूत्रसङ्ख्या। समाहितम्

2021-09-15 12:02 UTC, merged

2021-09-15 12:03 UTC, vvasuki commented on yajuH/taittirIyam/sUtram/ApastambaH/dharma-sUtram/kriyAH/shaucham/AnandaH.md
> +२२
अधुनापि दृश्यते ऽत्र?