Update 02_somayAganirUpaNam.md
vishvAsa/vedAH pull request #221
Opened 2023-11-09 18:10 UTC by brahmanarayana

2023-11-10 01:02 UTC, vvasuki requested changes

2023-11-10 01:02 UTC, vvasuki commented on meta/kalpaH/shrautam/articles/yajna-tattva-prakAshaH/02_somayAganirUpaNam.md
> +##सोमयागनिरूपणम्
इदं यथापूर्वम् एव करोतु। अत्रेमे दोषाः - 

`## ` इति चिह्नं केवलं भागसूचनार्थं प्रयोक्तव्यम्। एतादृशपङ्क्तयः विषयसूचिनिर्माणे प्रयोक्ष्यन्ते। 
तेन बृहद्भिरक्षरैर् दर्शनम् एव तत्प्रयोगायायानुचितं निधानम्।  
तस्य स्थाने `**॥ यज्ञतत्त्वप्रकाशः ॥**`` इति कृते **॥ यज्ञतत्त्वप्रकाशः ॥** इति दर्शयिष्यति।

2023-11-10 01:02 UTC, vvasuki commented on meta/kalpaH/shrautam/articles/yajna-tattva-prakAshaH/02_somayAganirUpaNam.md
> +##सोमयागेऽधिकारी
`##` चिह्नात् परम् एको रिक्तावकाशो ऽनिवार्यः। अन्यथा फलम् असमीचीनम् भवति। वीक्षताम् अन्तरम् - 

##सोमयागेऽधिकारी 

## सोमयागेऽधिकारी 

एवं सर्वत्र परिष्कृत्यात्रैव सूचयतु।

2023-11-10 16:49 UTC, brahmanarayana commented on meta/kalpaH/shrautam/articles/yajna-tattva-prakAshaH/02_somayAganirUpaNam.md
> +##सोमयागनिरूपणम्
कृतम्

2023-11-10 16:49 UTC, brahmanarayana commented on meta/kalpaH/shrautam/articles/yajna-tattva-prakAshaH/02_somayAganirUpaNam.md
> +##सोमयागेऽधिकारी
कृतम्

2023-11-11 01:22 UTC, vvasuki commented on meta/kalpaH/shrautam/articles/yajna-tattva-prakAshaH/02_somayAganirUpaNam.md
> +##सोमयागनिरूपणम्
क्षम्यताम्। मया टङ्कने दोषः कृतः। अधुना सम्पादितम्। पुनरीक्षताम्।

2023-11-11 21:51 UTC, merged